sudo: false
language: ruby
rvm:
 - 2.3
cache:
  bundler: true
  directories:
    - node_modules

script:
  - npm install
  - bundle exec jekyll build
  - gulp compress

before_deploy:
  - chmod +x deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
